apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  JWT_SECRET_KEY: change-this-in-production
  MONGO_URI: mongodb://root:example@mongodb-service.muchtodo.svc.cluster.local:27017/much_todo_db?authSource=admin
